# Generated by Django 2.1.3 on 2018-11-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='cursor_coordinates',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='domain',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='log',
            name='username',
            field=models.CharField(db_index=True, default='I', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='window_coordinates',
            field=models.CharField(default='', max_length=30),
        ),
    ]
