# Generated by Django 2.1.3 on 2018-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_easy'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='local_time',
            field=models.DateTimeField(default=None),
        ),
    ]
