# Generated by Django 2.1.3 on 2018-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0004_log_local_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='url',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
