# Generated by Django 2.1.3 on 2018-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_auto_20181108_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='cursor_coordinates',
        ),
        migrations.RemoveField(
            model_name='log',
            name='window_coordinates',
        ),
        migrations.AddField(
            model_name='log',
            name='x1_window_coordinates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='x2_window_coordinates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='x_cursor_coordinates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='y1_window_coordinates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='y2_window_coordinates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='y_cursor_coordinates',
            field=models.IntegerField(default=0),
        ),
    ]
