# Generated by Django 2.1.3 on 2018-12-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0006_auto_20181108_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField()),
                ('url1', models.TextField(db_index=True, default='')),
                ('domain1', models.CharField(db_index=True, default='', max_length=100)),
                ('time2', models.DateTimeField()),
                ('url2', models.TextField(db_index=True, default='')),
                ('domain2', models.CharField(db_index=True, default='', max_length=100)),
                ('two_url', models.TextField(db_index=True, default='')),
                ('two_domains', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Easy',
        ),
    ]
