# Generated by Django 2.1.3 on 2018-12-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0007_auto_20181231_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='threegrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField()),
                ('url1', models.TextField(db_index=True, default='')),
                ('domain1', models.CharField(db_index=True, default='', max_length=100)),
                ('time2', models.DateTimeField()),
                ('url2', models.TextField(db_index=True, default='')),
                ('domain2', models.CharField(db_index=True, default='', max_length=100)),
                ('time3', models.DateTimeField()),
                ('url3', models.TextField(db_index=True, default='')),
                ('domain3', models.CharField(db_index=True, default='', max_length=100)),
                ('three_urls', models.TextField(db_index=True, default='')),
                ('three_domains', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='bigrams',
            old_name='two_url',
            new_name='two_urls',
        ),
    ]
