# Generated by Django 2.1.3 on 2019-01-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0008_auto_20181231_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigrams',
            name='seance',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AddField(
            model_name='threegrams',
            name='seance',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
