# Generated by Django 2.1.3 on 2019-01-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0009_auto_20190101_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='threegrams',
            new_name='Trigrams',
        ),
    ]
