# Generated by Django 2.1.3 on 2019-01-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0014_auto_20190101_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigrams',
            name='username',
            field=models.CharField(db_index=True, default='I', max_length=50),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='username',
            field=models.CharField(db_index=True, default='I', max_length=50),
        ),
    ]
