# Generated by Django 2.1.3 on 2019-01-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0017_auto_20190101_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vectors',
        ),
    ]
