# Generated by Django 2.1.3 on 2019-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0018_delete_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='thousand',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
