# Generated by Django 2.1.3 on 2019-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0020_urlinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='I', max_length=50)),
                ('team', models.IntegerField(db_index=True)),
                ('frequent_urls', models.TextField(default='')),
                ('frequent_bi_urls', models.TextField(default='')),
                ('frequent_tri_urls', models.TextField(default='')),
                ('frequent_domains', models.TextField(default='')),
                ('frequent_bi_domains', models.TextField(default='')),
                ('frequent_tri_domains', models.TextField(default='')),
                ('frequent_bi_categorys', models.TextField(default='')),
                ('frequent_bi_types', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='bigrams',
            name='category1',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='bigrams',
            name='category2',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='bigrams',
            name='type1',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='bigrams',
            name='type2',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='category1',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='category2',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='category3',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='type1',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='type2',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='trigrams',
            name='type3',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
