# Generated by Django 2.1.3 on 2019-02-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0021_auto_20190212_1224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLInfo',
            new_name='URLs',
        ),
    ]
