# Generated by Django 2.1.3 on 2019-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0022_auto_20190212_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=100)),
                ('type', models.TextField(db_index=True, default='')),
                ('category', models.TextField(db_index=True, default='')),
            ],
        ),
    ]
