# Generated by Django 2.1.3 on 2019-03-05 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0023_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='frequent_bi_categorys',
        ),
        migrations.RemoveField(
            model_name='users',
            name='frequent_bi_types',
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_bi_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_bi_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_tri_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_tri_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
    ]
