# Generated by Django 2.1.3 on 2019-03-05 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0024_auto_20190305_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='frequent_bi_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_bi_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_tri_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_tri_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=None),
        ),
    ]
