# Generated by Django 2.1.3 on 2019-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0025_auto_20190305_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='thousand',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
