# Generated by Django 2.1.3 on 2019-03-08 21:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0029_users_frequent_domains_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='frequent_domains_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='frequent_domains_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None),
        ),
    ]
