# Generated by Django 2.1.3 on 2019-03-09 00:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0030_auto_20190309_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='frequent_domains_type',
        ),
        migrations.AddField(
            model_name='users',
            name='frequent_bi_domains_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='users',
            name='frequent_bi_domains_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='users',
            name='frequent_tri_domains_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='users',
            name='frequent_tri_domains_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None),
        ),
    ]
