# Generated by Django 2.1.3 on 2019-03-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0033_auto_20190312_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='domains',
            name='id',
        ),
        migrations.AlterField(
            model_name='domains',
            name='domain',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='new',
            name='domain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyse.Domains'),
        ),
    ]
