# Generated by Django 2.1.3 on 2019-03-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0034_auto_20190312_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domains',
            old_name='domain_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='domains',
            old_name='domain_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='bigrams',
            name='domain_category1',
        ),
        migrations.RemoveField(
            model_name='bigrams',
            name='domain_category2',
        ),
        migrations.RemoveField(
            model_name='bigrams',
            name='domain_type1',
        ),
        migrations.RemoveField(
            model_name='bigrams',
            name='domain_type2',
        ),
        migrations.RemoveField(
            model_name='log',
            name='domain_category',
        ),
        migrations.RemoveField(
            model_name='log',
            name='domain_type',
        ),
        migrations.RemoveField(
            model_name='trigrams',
            name='domain_category1',
        ),
        migrations.RemoveField(
            model_name='trigrams',
            name='domain_category2',
        ),
        migrations.RemoveField(
            model_name='trigrams',
            name='domain_category3',
        ),
        migrations.RemoveField(
            model_name='trigrams',
            name='domain_type1',
        ),
        migrations.RemoveField(
            model_name='trigrams',
            name='domain_type2',
        ),
        migrations.RemoveField(
            model_name='trigrams',
            name='domain_type3',
        ),
        migrations.AlterField(
            model_name='bigrams',
            name='domain1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_domain_in_bi', to='analyse.Domains'),
        ),
        migrations.AlterField(
            model_name='bigrams',
            name='domain2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_domain_in_bi', to='analyse.Domains'),
        ),
        migrations.AlterField(
            model_name='log',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Domains'),
        ),
        migrations.AlterField(
            model_name='trigrams',
            name='domain1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_domain_in_tri', to='analyse.Domains'),
        ),
        migrations.AlterField(
            model_name='trigrams',
            name='domain2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_domain_in_tri', to='analyse.Domains'),
        ),
        migrations.AlterField(
            model_name='trigrams',
            name='domain3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_domain_in_tri', to='analyse.Domains'),
        ),
    ]
