# Generated by Django 2.1.3 on 2019-03-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0035_auto_20190313_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='domain',
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
