# Generated by Django 2.1.3 on 2019-03-13 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0037_auto_20190313_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(db_index=True)),
                ('username', models.CharField(db_index=True, default='I', max_length=50)),
                ('frequent_urls', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('frequent_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), size=None)),
                ('frequent_domains_categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None)),
                ('frequent_bi_urls', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=None)),
                ('frequent_tri_urls', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=None)),
                ('frequent_bi_domains', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), size=None), size=None)),
                ('frequent_tri_domains', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), size=None), size=None)),
                ('frequent_bi_domains_type', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None)),
                ('frequent_bi_domains_categories', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None)),
                ('frequent_tri_domains_type', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None)),
                ('frequent_tri_domains_categories', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), default=list, size=None)),
                ('thousand', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
