# Generated by Django 2.1.3 on 2019-03-14 10:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0038_auto_20190313_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorsOneVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(db_index=True)),
                ('thousand', models.IntegerField(db_index=True, default=0)),
                ('username', models.CharField(db_index=True, default='I', max_length=50)),
                ('number_parts_per_day', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('day_parts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('middle_pause', models.FloatField(default=0)),
                ('start_comp_pause', models.FloatField(default=0)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('url_freq_pause', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None)),
                ('url_maps', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('dom_freq_pause', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None)),
                ('domain_maps', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('url_bi', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('url_bi_pauses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('dom_bi', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('dom_bi_pauses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('url_tri', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('url_tri_pauses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('dom_tri', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('dom_tri_pauses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('domain_type', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('domain_categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
            ],
        ),
    ]
