# Generated by Django 2.1.3 on 2019-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0039_vectorsoneversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorsoneversion',
            name='type',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
