# Generated by Django 2.1.3 on 2019-03-15 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0040_vectorsoneversion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='dom_bi_pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None),
        ),
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='dom_tri_pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None),
        ),
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='domain_maps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='url_bi_pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None),
        ),
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='url_maps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='url_tri_pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=None),
        ),
    ]
