# Generated by Django 2.1.3 on 2019-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0041_auto_20190315_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorsoneversion',
            name='middle_pause2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vectorsoneversion',
            name='middle_pause3',
            field=models.FloatField(default=0),
        ),
    ]
