# Generated by Django 2.1.3 on 2019-03-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0042_auto_20190325_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorsoneversion',
            name='quantity_middle_pause',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vectorsoneversion',
            name='quantity_middle_pause2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vectorsoneversion',
            name='quantity_middle_pause3',
            field=models.IntegerField(default=0),
        ),
    ]
