# Generated by Django 2.1.3 on 2019-03-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0044_auto_20190327_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml',
            name='algorithm',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
