# Generated by Django 2.1.3 on 2019-03-27 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0045_ml_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
            ],
        ),
    ]
