# Generated by Django 2.1.3 on 2019-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0047_auto_20190330_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorsoneversion',
            name='last_click',
            field=models.IntegerField(default=0),
        ),
    ]
