# Generated by Django 2.1.3 on 2019-03-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0048_auto_20190330_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectorsoneversion',
            name='last_click',
        ),
    ]
