# Generated by Django 2.1.3 on 2019-03-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0050_auto_20190330_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorsoneversion1',
            name='last_click',
            field=models.IntegerField(default=0),
        ),
    ]
