# Generated by Django 2.1.3 on 2019-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0051_vectorsoneversion1_last_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(db_index=True)),
                ('thousand', models.IntegerField(db_index=True, default=0)),
                ('users_quantity', models.IntegerField(db_index=True, default=0)),
                ('number_parts_per_day', models.IntegerField(default=0)),
            ],
        ),
    ]
