# Generated by Django 2.1.3 on 2019-03-30 19:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0052_basecollections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineMLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
                ('patterns', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('middleFAR', models.FloatField(default=0.0)),
                ('middleFRR', models.FloatField(default=0.0)),
                ('algorithm', models.TextField(db_index=True, default='')),
                ('collection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyse.BaseCollections')),
            ],
        ),
    ]
