# Generated by Django 2.1.3 on 2019-04-01 07:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0053_combinemls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorsoneversion1',
            name='activity_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
