# Generated by Django 2.1.3 on 2019-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0054_auto_20190401_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorsoneversion1',
            name='num_unique_domains',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vectorsoneversion1',
            name='num_unique_urls',
            field=models.IntegerField(default=0),
        ),
    ]
