# Generated by Django 2.1.3 on 2019-04-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0055_auto_20190402_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectorsoneversion1',
            name='num_unique_domains',
        ),
        migrations.RemoveField(
            model_name='vectorsoneversion1',
            name='num_unique_urls',
        ),
    ]
