# Generated by Django 2.1.3 on 2019-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0057_auto_20190402_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains2',
            fields=[
                ('domain', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('type', models.TextField(db_index=True, default='')),
                ('category', models.TextField(db_index=True, default='')),
            ],
        ),
    ]
