# Generated by Django 2.1.3 on 2019-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0059_remove_collections_thousand'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='num_vectors',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
