# Generated by Django 2.1.3 on 2019-04-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0064_vectorsoneversion3_vectorsoneversion4'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='num_group',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
