# Generated by Django 2.1.3 on 2019-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0065_patterns_num_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml',
            name='num_group',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
